export enum eMessageType {
  NotSet = 0,
  Error = 2,
  Warning = 4,
  Message = 8,
  Success = 16,
  Unknown = 32,
  NotApplicable = 64,
  NoResponse = 128,
  Email = 256,
}
export enum eSensorType {
  NotSet = 1,
  CriticalError = 2,
  DegradedFunctionality = 4,
  Operational = 0x10,
}
export enum eCodeLanguage {
  NotSet = 0,
  CSharp = 1,
  Php = 2,
  JS = 3,
  ActionScript = 4,
  ColdFusion = 5,
  Bash = 6,
  Delphi = 7,
  Java = 8,
  Perl = 9,
  Python = 10,
  Ruby = 11,
  VisualBasic = 12,
  SQL = 13,
}
export enum eValueType {
  Text = 0,
  TextFormated = 1,
  HTML = 10,
  XML = 12,
  URL = 15,
  JSON = 20,
  Code = 30,
  CSV = 40,
  Date = 100,
  Time = 101,
  DateTime = 102,
  Duration = 105,
  Number = 110,
}
